#!/usr/bin/perl -w

use KBS2::Util;
use PerlLib::SwissArmyKnife;
use UniLang::Util::TempAgent;

my $tempagent = UniLang::Util::TempAgent->new();

my $res = $tempagent->MyAgent->QueryAgent
  (
   Receiver => 'Agent1',
   Data => {
	    Eval => [['_prolog_list',Var('?X'),['completed',Var('?X')]]],
	   },
  );

my $res2 = $res->{Data}{Result};
print Dumper($res2);
