#!/usr/bin/perl -w

use KBS2::Util;
use PerlLib::SwissArmyKnife;
use UniLang::Util::TempAgent;

my $tempagent = UniLang::Util::TempAgent->new();

my $input;
do {
  $input = QueryUser("> ");
  if (NotAnExitCommand(Input => $input)) {
    my $res;
    if ($input =~ /u/i) {
      print "UniLang\n";
      $res = $tempagent->MyAgent->QueryAgent
	(
	 Receiver => 'Agent1',
	 Data => {
		  Eval => [['_prolog_list',Var('?X'),['completed',Var('?X')]]],
		 },
	);
    } elsif ($input =~ /d/i) {
      print "Directly\n";
      $res = $tempagent->MyAgent->QueryAgent
	(
	 Receiver => 'Test',
	 Data => {
		  Command => 'queryInternalYaswi',
		  AgentName => 'Agent1',
		  YaswiName => 'Yaswi1',
		  QueryData => {
				ThisIsATest => 1,
			       },
		 },
	);
    }
    print Dumper($res);
  }
} while (NotAnExitCommand(Input => $input));
print "done\n";

sub NotAnExitCommand {
  my (%args) = @_;
  $args{Input} !~ /^(exit|halt|quit).$/i;
}
